const sectionDefaults = {
  hero: {
    type: 'hero',
    name: 'Hero Section',
    visible: true,
    published: true,
    order: 0,
    content: {
      title: 'Your Name',
      subtitle: 'Your Title / Role',
      description: 'A short professional description that introduces yourself to visitors.',
      buttons: [
        { text: 'Get in Touch', url: '#contact', style: 'primary', icon: '' },
        { text: 'View Projects', url: '#projects', style: 'outline', icon: '' },
      ],
      socialLinks: [
        { platform: 'github', url: 'https://github.com/yourname', icon: '' },
        { platform: 'linkedin', url: 'https://linkedin.com/in/yourname', icon: '' },
      ],
      image: '',
      video: '',
    },
    style: {
      background: '#ffffff',
      textColor: '#1a1a2e',
      headingColor: '#0f0f23',
      linkColor: '#3b82f6',
      buttonStyle: 'rounded',
      cardStyle: 'default',
      iconStyle: 'default',
      spacing: 'comfortable',
      shadow: 'none',
      borderRadius: '0',
      opacity: 100,
      hoverState: 'none',
      focusState: 'none',
    },
    layout: {
      containerWidth: 'boxed',
      padding: '80px 0',
      margin: '0',
      sectionHeight: 'auto',
      alignment: 'center',
      columns: 1,
      gap: '0',
      flexDirection: 'column',
      sticky: false,
    },
    media: {
      backgroundImage: '',
      backgroundVideo: '',
      overlayColor: '',
      overlayOpacity: 0,
      parallax: false,
    },
    seo: {
      metaTitle: '',
      metaDescription: '',
      keywords: '',
      slug: '',
      ogTitle: '',
      ogDescription: '',
      ogImage: '',
    },
    animation: {
      type: 'fade',
      duration: 1,
      delay: 0,
      trigger: 'onLoad',
      loop: false,
      scrollAnimation: 'none',
    },
    responsive: {
      desktop: { visible: true, fontSize: 100, spacing: 100, layout: 'default', order: 0, imageSize: 100 },
      tablet: { visible: true, fontSize: 85, spacing: 80, layout: 'stacked', order: 0, imageSize: 80 },
      mobile: { visible: true, fontSize: 70, spacing: 60, layout: 'stacked', order: 0, imageSize: 60 },
    },
    permissions: { roleVisibility: 'All', passwordProtect: false },
    analytics: { viewCount: 0, clickTracking: false, scrollDepthTracking: false },
    advanced: { customCSS: '', customAttributes: '', customID: '' },
    versionHistory: [],
  },

  about: {
    type: 'about',
    name: 'About Section',
    visible: true,
    published: true,
    order: 0,
    content: {
      title: 'About Me',
      subtitle: 'A brief story about who I am',
      description: 'Write a compelling biography that tells visitors about your background, passion, and what drives you.',
      image: '',
      stats: [
        { label: 'Years Experience', value: '5+' },
        { label: 'Projects Completed', value: '50+' },
        { label: 'Happy Clients', value: '30+' },
      ],
      buttons: [{ text: 'Download CV', url: '#', style: 'primary', icon: 'download' }],
    },
    style: { background: '#f8f9fa', textColor: '#333333', headingColor: '#1a1a2e', linkColor: '#3b82f6', buttonStyle: 'rounded', cardStyle: 'default', iconStyle: 'default', spacing: 'comfortable', shadow: 'none', borderRadius: '0', opacity: 100, hoverState: 'none', focusState: 'none' },
    layout: { containerWidth: 'boxed', padding: '80px 0', margin: '0', sectionHeight: 'auto', alignment: 'center', columns: 2, gap: '40px', flexDirection: 'row', sticky: false },
    media: { backgroundImage: '', backgroundVideo: '', overlayColor: '', overlayOpacity: 0, parallax: false },
    seo: { metaTitle: '', metaDescription: '', keywords: '', slug: '', ogTitle: '', ogDescription: '', ogImage: '' },
    animation: { type: 'slide', duration: 1, delay: 0, trigger: 'onScroll', loop: false, scrollAnimation: 'none' },
    responsive: { desktop: { visible: true, fontSize: 100, spacing: 100, layout: 'default', order: 0, imageSize: 100 }, tablet: { visible: true, fontSize: 85, spacing: 80, layout: 'stacked', order: 0, imageSize: 80 }, mobile: { visible: true, fontSize: 70, spacing: 60, layout: 'stacked', order: 0, imageSize: 60 } },
    permissions: { roleVisibility: 'All', passwordProtect: false },
    analytics: { viewCount: 0, clickTracking: false, scrollDepthTracking: false },
    advanced: { customCSS: '', customAttributes: '', customID: '' },
    versionHistory: [],
  },

  projects: {
    type: 'projects',
    name: 'Projects Section',
    visible: true,
    published: true,
    order: 0,
    content: {
      title: 'My Projects',
      subtitle: 'Featured work and side projects',
      description: '',
      filterable: true,
      columns: 3,
      showFilters: true,
      categories: ['All', 'Web', 'Mobile', 'Design'],
    },
    style: { background: '#ffffff', textColor: '#333333', headingColor: '#1a1a2e', linkColor: '#3b82f6', buttonStyle: 'rounded', cardStyle: 'shadow', iconStyle: 'default', spacing: 'comfortable', shadow: 'medium', borderRadius: '12', opacity: 100, hoverState: 'lift', focusState: 'none' },
    layout: { containerWidth: 'boxed', padding: '80px 0', margin: '0', sectionHeight: 'auto', alignment: 'center', columns: 3, gap: '24px', flexDirection: 'row', sticky: false },
    media: { backgroundImage: '', backgroundVideo: '', overlayColor: '', overlayOpacity: 0, parallax: false },
    seo: { metaTitle: '', metaDescription: '', keywords: '', slug: '', ogTitle: '', ogDescription: '', ogImage: '' },
    animation: { type: 'fade', duration: 1, delay: 0.2, trigger: 'onScroll', loop: false, scrollAnimation: 'none' },
    responsive: { desktop: { visible: true, fontSize: 100, spacing: 100, layout: 'default', order: 0, imageSize: 100 }, tablet: { visible: true, fontSize: 85, spacing: 80, layout: 'grid-2', order: 0, imageSize: 80 }, mobile: { visible: true, fontSize: 70, spacing: 60, layout: 'stacked', order: 0, imageSize: 60 } },
    permissions: { roleVisibility: 'All', passwordProtect: false },
    analytics: { viewCount: 0, clickTracking: true, scrollDepthTracking: false },
    advanced: { customCSS: '', customAttributes: '', customID: '' },
    versionHistory: [],
  },

  skills: {
    type: 'skills',
    name: 'Skills Section',
    visible: true,
    published: true,
    order: 0,
    content: {
      title: 'My Skills',
      subtitle: 'Technologies and tools I work with',
      description: '',
      layout: 'bars',
      columns: 2,
      showProficiency: true,
    },
    style: { background: '#f8f9fa', textColor: '#333333', headingColor: '#1a1a2e', linkColor: '#3b82f6', buttonStyle: 'rounded', cardStyle: 'default', iconStyle: 'default', spacing: 'compact', shadow: 'none', borderRadius: '0', opacity: 100, hoverState: 'none', focusState: 'none' },
    layout: { containerWidth: 'boxed', padding: '80px 0', margin: '0', sectionHeight: 'auto', alignment: 'center', columns: 2, gap: '32px', flexDirection: 'row', sticky: false },
    media: { backgroundImage: '', backgroundVideo: '', overlayColor: '', overlayOpacity: 0, parallax: false },
    seo: { metaTitle: '', metaDescription: '', keywords: '', slug: '', ogTitle: '', ogDescription: '', ogImage: '' },
    animation: { type: 'fade', duration: 0.8, delay: 0.1, trigger: 'onScroll', loop: false, scrollAnimation: 'none' },
    responsive: { desktop: { visible: true, fontSize: 100, spacing: 100, layout: 'default', order: 0, imageSize: 100 }, tablet: { visible: true, fontSize: 85, spacing: 80, layout: 'stacked', order: 0, imageSize: 80 }, mobile: { visible: true, fontSize: 70, spacing: 60, layout: 'stacked', order: 0, imageSize: 60 } },
    permissions: { roleVisibility: 'All', passwordProtect: false },
    analytics: { viewCount: 0, clickTracking: false, scrollDepthTracking: false },
    advanced: { customCSS: '', customAttributes: '', customID: '' },
    versionHistory: [],
  },

  experience: {
    type: 'experience',
    name: 'Experience Section',
    visible: true,
    published: true,
    order: 0,
    content: {
      title: 'Work Experience',
      subtitle: 'My professional journey',
      description: '',
      layout: 'alternating',
    },
    style: { background: '#ffffff', textColor: '#333333', headingColor: '#1a1a2e', linkColor: '#3b82f6', buttonStyle: 'rounded', cardStyle: 'default', iconStyle: 'default', spacing: 'comfortable', shadow: 'none', borderRadius: '0', opacity: 100, hoverState: 'none', focusState: 'none' },
    layout: { containerWidth: 'boxed', padding: '80px 0', margin: '0', sectionHeight: 'auto', alignment: 'center', columns: 1, gap: '0', flexDirection: 'column', sticky: false },
    media: { backgroundImage: '', backgroundVideo: '', overlayColor: '', overlayOpacity: 0, parallax: false },
    seo: { metaTitle: '', metaDescription: '', keywords: '', slug: '', ogTitle: '', ogDescription: '', ogImage: '' },
    animation: { type: 'slide', duration: 0.8, delay: 0, trigger: 'onScroll', loop: false, scrollAnimation: 'reveal' },
    responsive: { desktop: { visible: true, fontSize: 100, spacing: 100, layout: 'default', order: 0, imageSize: 100 }, tablet: { visible: true, fontSize: 85, spacing: 80, layout: 'default', order: 0, imageSize: 80 }, mobile: { visible: true, fontSize: 70, spacing: 60, layout: 'stacked', order: 0, imageSize: 60 } },
    permissions: { roleVisibility: 'All', passwordProtect: false },
    analytics: { viewCount: 0, clickTracking: false, scrollDepthTracking: false },
    advanced: { customCSS: '', customAttributes: '', customID: '' },
    versionHistory: [],
  },

  education: {
    type: 'education',
    name: 'Education Section',
    visible: true,
    published: true,
    order: 0,
    content: {
      title: 'Education',
      subtitle: 'Academic background',
      description: '',
      layout: 'cards',
    },
    style: { background: '#f8f9fa', textColor: '#333333', headingColor: '#1a1a2e', linkColor: '#3b82f6', buttonStyle: 'rounded', cardStyle: 'shadow', iconStyle: 'default', spacing: 'comfortable', shadow: 'small', borderRadius: '12', opacity: 100, hoverState: 'lift', focusState: 'none' },
    layout: { containerWidth: 'boxed', padding: '80px 0', margin: '0', sectionHeight: 'auto', alignment: 'center', columns: 2, gap: '24px', flexDirection: 'row', sticky: false },
    media: { backgroundImage: '', backgroundVideo: '', overlayColor: '', overlayOpacity: 0, parallax: false },
    seo: { metaTitle: '', metaDescription: '', keywords: '', slug: '', ogTitle: '', ogDescription: '', ogImage: '' },
    animation: { type: 'fade', duration: 0.8, delay: 0.1, trigger: 'onScroll', loop: false, scrollAnimation: 'none' },
    responsive: { desktop: { visible: true, fontSize: 100, spacing: 100, layout: 'default', order: 0, imageSize: 100 }, tablet: { visible: true, fontSize: 85, spacing: 80, layout: 'grid-2', order: 0, imageSize: 80 }, mobile: { visible: true, fontSize: 70, spacing: 60, layout: 'stacked', order: 0, imageSize: 60 } },
    permissions: { roleVisibility: 'All', passwordProtect: false },
    analytics: { viewCount: 0, clickTracking: false, scrollDepthTracking: false },
    advanced: { customCSS: '', customAttributes: '', customID: '' },
    versionHistory: [],
  },

  certificates: {
    type: 'certificates',
    name: 'Certificates Section',
    visible: true,
    published: true,
    order: 0,
    content: {
      title: 'Certificates',
      subtitle: 'Professional certifications and achievements',
      description: '',
      columns: 3,
    },
    style: { background: '#ffffff', textColor: '#333333', headingColor: '#1a1a2e', linkColor: '#3b82f6', buttonStyle: 'rounded', cardStyle: 'shadow', iconStyle: 'default', spacing: 'comfortable', shadow: 'small', borderRadius: '12', opacity: 100, hoverState: 'lift', focusState: 'none' },
    layout: { containerWidth: 'boxed', padding: '80px 0', margin: '0', sectionHeight: 'auto', alignment: 'center', columns: 3, gap: '24px', flexDirection: 'row', sticky: false },
    media: { backgroundImage: '', backgroundVideo: '', overlayColor: '', overlayOpacity: 0, parallax: false },
    seo: { metaTitle: '', metaDescription: '', keywords: '', slug: '', ogTitle: '', ogDescription: '', ogImage: '' },
    animation: { type: 'zoom', duration: 0.6, delay: 0.1, trigger: 'onScroll', loop: false, scrollAnimation: 'none' },
    responsive: { desktop: { visible: true, fontSize: 100, spacing: 100, layout: 'default', order: 0, imageSize: 100 }, tablet: { visible: true, fontSize: 85, spacing: 80, layout: 'grid-2', order: 0, imageSize: 80 }, mobile: { visible: true, fontSize: 70, spacing: 60, layout: 'stacked', order: 0, imageSize: 60 } },
    permissions: { roleVisibility: 'All', passwordProtect: false },
    analytics: { viewCount: 0, clickTracking: false, scrollDepthTracking: false },
    advanced: { customCSS: '', customAttributes: '', customID: '' },
    versionHistory: [],
  },

  testimonials: {
    type: 'testimonials',
    name: 'Testimonials Section',
    visible: true,
    published: true,
    order: 0,
    content: {
      title: 'What People Say',
      subtitle: 'Testimonials from clients and colleagues',
      description: '',
      layout: 'grid',
      autoplay: true,
      autoplaySpeed: 5000,
    },
    style: { background: '#f8f9fa', textColor: '#333333', headingColor: '#1a1a2e', linkColor: '#3b82f6', buttonStyle: 'rounded', cardStyle: 'shadow', iconStyle: 'default', spacing: 'comfortable', shadow: 'small', borderRadius: '12', opacity: 100, hoverState: 'none', focusState: 'none' },
    layout: { containerWidth: 'boxed', padding: '80px 0', margin: '0', sectionHeight: 'auto', alignment: 'center', columns: 2, gap: '24px', flexDirection: 'row', sticky: false },
    media: { backgroundImage: '', backgroundVideo: '', overlayColor: '', overlayOpacity: 0, parallax: false },
    seo: { metaTitle: '', metaDescription: '', keywords: '', slug: '', ogTitle: '', ogDescription: '', ogImage: '' },
    animation: { type: 'fade', duration: 0.8, delay: 0, trigger: 'onScroll', loop: false, scrollAnimation: 'none' },
    responsive: { desktop: { visible: true, fontSize: 100, spacing: 100, layout: 'default', order: 0, imageSize: 100 }, tablet: { visible: true, fontSize: 85, spacing: 80, layout: 'grid-2', order: 0, imageSize: 80 }, mobile: { visible: true, fontSize: 70, spacing: 60, layout: 'stacked', order: 0, imageSize: 60 } },
    permissions: { roleVisibility: 'All', passwordProtect: false },
    analytics: { viewCount: 0, clickTracking: false, scrollDepthTracking: false },
    advanced: { customCSS: '', customAttributes: '', customID: '' },
    versionHistory: [],
  },

  services: {
    type: 'services',
    name: 'Services Section',
    visible: true,
    published: true,
    order: 0,
    content: {
      title: 'My Services',
      subtitle: 'What I can do for you',
      description: '',
      columns: 3,
    },
    style: { background: '#ffffff', textColor: '#333333', headingColor: '#1a1a2e', linkColor: '#3b82f6', buttonStyle: 'rounded', cardStyle: 'shadow', iconStyle: 'large', spacing: 'comfortable', shadow: 'small', borderRadius: '12', opacity: 100, hoverState: 'lift', focusState: 'none' },
    layout: { containerWidth: 'boxed', padding: '80px 0', margin: '0', sectionHeight: 'auto', alignment: 'center', columns: 3, gap: '24px', flexDirection: 'row', sticky: false },
    media: { backgroundImage: '', backgroundVideo: '', overlayColor: '', overlayOpacity: 0, parallax: false },
    seo: { metaTitle: '', metaDescription: '', keywords: '', slug: '', ogTitle: '', ogDescription: '', ogImage: '' },
    animation: { type: 'fade', duration: 0.8, delay: 0.1, trigger: 'onScroll', loop: false, scrollAnimation: 'none' },
    responsive: { desktop: { visible: true, fontSize: 100, spacing: 100, layout: 'default', order: 0, imageSize: 100 }, tablet: { visible: true, fontSize: 85, spacing: 80, layout: 'grid-2', order: 0, imageSize: 80 }, mobile: { visible: true, fontSize: 70, spacing: 60, layout: 'stacked', order: 0, imageSize: 60 } },
    permissions: { roleVisibility: 'All', passwordProtect: false },
    analytics: { viewCount: 0, clickTracking: false, scrollDepthTracking: false },
    advanced: { customCSS: '', customAttributes: '', customID: '' },
    versionHistory: [],
  },

  blog: {
    type: 'blog',
    name: 'Blog Section',
    visible: true,
    published: true,
    order: 0,
    content: {
      title: 'Latest Posts',
      subtitle: 'Thoughts and articles',
      description: '',
      showCount: 3,
      columns: 3,
      showExcerpt: true,
      showDate: true,
      showReadMore: true,
    },
    style: { background: '#f8f9fa', textColor: '#333333', headingColor: '#1a1a2e', linkColor: '#3b82f6', buttonStyle: 'rounded', cardStyle: 'shadow', iconStyle: 'default', spacing: 'comfortable', shadow: 'small', borderRadius: '12', opacity: 100, hoverState: 'lift', focusState: 'none' },
    layout: { containerWidth: 'boxed', padding: '80px 0', margin: '0', sectionHeight: 'auto', alignment: 'center', columns: 3, gap: '24px', flexDirection: 'row', sticky: false },
    media: { backgroundImage: '', backgroundVideo: '', overlayColor: '', overlayOpacity: 0, parallax: false },
    seo: { metaTitle: '', metaDescription: '', keywords: '', slug: '', ogTitle: '', ogDescription: '', ogImage: '' },
    animation: { type: 'fade', duration: 0.8, delay: 0.1, trigger: 'onScroll', loop: false, scrollAnimation: 'none' },
    responsive: { desktop: { visible: true, fontSize: 100, spacing: 100, layout: 'default', order: 0, imageSize: 100 }, tablet: { visible: true, fontSize: 85, spacing: 80, layout: 'grid-2', order: 0, imageSize: 80 }, mobile: { visible: true, fontSize: 70, spacing: 60, layout: 'stacked', order: 0, imageSize: 60 } },
    permissions: { roleVisibility: 'All', passwordProtect: false },
    analytics: { viewCount: 0, clickTracking: true, scrollDepthTracking: true },
    advanced: { customCSS: '', customAttributes: '', customID: '' },
    versionHistory: [],
  },

  contact: {
    type: 'contact',
    name: 'Contact Section',
    visible: true,
    published: true,
    order: 0,
    content: {
      title: 'Get In Touch',
      subtitle: 'Have a question or want to work together?',
      description: 'Feel free to reach out for collaborations, opportunities, or just a friendly chat.',
      recipientEmail: '',
      showPhone: true,
      showAddress: true,
      socialLinks: [
        { platform: 'github', url: '', icon: '' },
        { platform: 'linkedin', url: '', icon: '' },
        { platform: 'twitter', url: '', icon: '' },
      ],
      address: '',
      phone: '',
      email: '',
    },
    style: { background: '#ffffff', textColor: '#333333', headingColor: '#1a1a2e', linkColor: '#3b82f6', buttonStyle: 'rounded', cardStyle: 'default', iconStyle: 'default', spacing: 'comfortable', shadow: 'none', borderRadius: '0', opacity: 100, hoverState: 'none', focusState: 'none' },
    layout: { containerWidth: 'boxed', padding: '80px 0', margin: '0', sectionHeight: 'auto', alignment: 'center', columns: 2, gap: '40px', flexDirection: 'row', sticky: false },
    media: { backgroundImage: '', backgroundVideo: '', overlayColor: '', overlayOpacity: 0, parallax: false },
    seo: { metaTitle: '', metaDescription: '', keywords: '', slug: '', ogTitle: '', ogDescription: '', ogImage: '' },
    animation: { type: 'fade', duration: 0.8, delay: 0, trigger: 'onScroll', loop: false, scrollAnimation: 'none' },
    responsive: { desktop: { visible: true, fontSize: 100, spacing: 100, layout: 'default', order: 0, imageSize: 100 }, tablet: { visible: true, fontSize: 85, spacing: 80, layout: 'stacked', order: 0, imageSize: 80 }, mobile: { visible: true, fontSize: 70, spacing: 60, layout: 'stacked', order: 0, imageSize: 60 } },
    permissions: { roleVisibility: 'All', passwordProtect: false },
    analytics: { viewCount: 0, clickTracking: true, scrollDepthTracking: false },
    advanced: { customCSS: '', customAttributes: '', customID: '' },
    versionHistory: [],
  },

  gallery: {
    type: 'gallery',
    name: 'Gallery Section',
    visible: true,
    published: true,
    order: 0,
    content: {
      title: 'Gallery',
      subtitle: 'Photo gallery',
      description: '',
      columns: 3,
      lightbox: true,
      aspectRatio: '4/3',
    },
    style: { background: '#f8f9fa', textColor: '#333333', headingColor: '#1a1a2e', linkColor: '#3b82f6', buttonStyle: 'rounded', cardStyle: 'default', iconStyle: 'default', spacing: 'comfortable', shadow: 'none', borderRadius: '8', opacity: 100, hoverState: 'zoom', focusState: 'none' },
    layout: { containerWidth: 'full', padding: '80px 0', margin: '0', sectionHeight: 'auto', alignment: 'center', columns: 3, gap: '12px', flexDirection: 'row', sticky: false },
    media: { backgroundImage: '', backgroundVideo: '', overlayColor: '', overlayOpacity: 0, parallax: false },
    seo: { metaTitle: '', metaDescription: '', keywords: '', slug: '', ogTitle: '', ogDescription: '', ogImage: '' },
    animation: { type: 'zoom', duration: 0.6, delay: 0.1, trigger: 'onScroll', loop: false, scrollAnimation: 'none' },
    responsive: { desktop: { visible: true, fontSize: 100, spacing: 100, layout: 'default', order: 0, imageSize: 100 }, tablet: { visible: true, fontSize: 85, spacing: 80, layout: 'grid-2', order: 0, imageSize: 80 }, mobile: { visible: true, fontSize: 70, spacing: 60, layout: 'stacked', order: 0, imageSize: 60 } },
    permissions: { roleVisibility: 'All', passwordProtect: false },
    analytics: { viewCount: 0, clickTracking: false, scrollDepthTracking: false },
    advanced: { customCSS: '', customAttributes: '', customID: '' },
    versionHistory: [],
  },

  timeline: {
    type: 'timeline',
    name: 'Timeline Section',
    visible: true,
    published: true,
    order: 0,
    content: {
      title: 'Timeline',
      subtitle: 'Key milestones and events',
      description: '',
      layout: 'alternating',
    },
    style: { background: '#ffffff', textColor: '#333333', headingColor: '#1a1a2e', linkColor: '#3b82f6', buttonStyle: 'rounded', cardStyle: 'default', iconStyle: 'default', spacing: 'comfortable', shadow: 'none', borderRadius: '0', opacity: 100, hoverState: 'none', focusState: 'none' },
    layout: { containerWidth: 'boxed', padding: '80px 0', margin: '0', sectionHeight: 'auto', alignment: 'center', columns: 1, gap: '0', flexDirection: 'column', sticky: false },
    media: { backgroundImage: '', backgroundVideo: '', overlayColor: '', overlayOpacity: 0, parallax: false },
    seo: { metaTitle: '', metaDescription: '', keywords: '', slug: '', ogTitle: '', ogDescription: '', ogImage: '' },
    animation: { type: 'slide', duration: 0.8, delay: 0, trigger: 'onScroll', loop: false, scrollAnimation: 'reveal' },
    responsive: { desktop: { visible: true, fontSize: 100, spacing: 100, layout: 'default', order: 0, imageSize: 100 }, tablet: { visible: true, fontSize: 85, spacing: 80, layout: 'default', order: 0, imageSize: 80 }, mobile: { visible: true, fontSize: 70, spacing: 60, layout: 'stacked', order: 0, imageSize: 60 } },
    permissions: { roleVisibility: 'All', passwordProtect: false },
    analytics: { viewCount: 0, clickTracking: false, scrollDepthTracking: false },
    advanced: { customCSS: '', customAttributes: '', customID: '' },
    versionHistory: [],
  },

  faq: {
    type: 'faq',
    name: 'FAQ Section',
    visible: true,
    published: true,
    order: 0,
    content: {
      title: 'Frequently Asked Questions',
      subtitle: 'Common questions and answers',
      description: '',
      items: [
        { question: 'What services do you offer?', answer: 'I offer a wide range of services including web development, mobile app development, and consulting.' },
        { question: 'What is your typical turnaround time?', answer: 'Project timelines vary depending on scope, but most projects are completed within 2-4 weeks.' },
      ],
      layout: 'accordion',
    },
    style: { background: '#f8f9fa', textColor: '#333333', headingColor: '#1a1a2e', linkColor: '#3b82f6', buttonStyle: 'rounded', cardStyle: 'default', iconStyle: 'default', spacing: 'comfortable', shadow: 'none', borderRadius: '8', opacity: 100, hoverState: 'none', focusState: 'none' },
    layout: { containerWidth: 'boxed', padding: '80px 0', margin: '0', sectionHeight: 'auto', alignment: 'center', columns: 1, gap: '0', flexDirection: 'column', sticky: false },
    media: { backgroundImage: '', backgroundVideo: '', overlayColor: '', overlayOpacity: 0, parallax: false },
    seo: { metaTitle: '', metaDescription: '', keywords: '', slug: '', ogTitle: '', ogDescription: '', ogImage: '' },
    animation: { type: 'fade', duration: 0.6, delay: 0, trigger: 'onScroll', loop: false, scrollAnimation: 'none' },
    responsive: { desktop: { visible: true, fontSize: 100, spacing: 100, layout: 'default', order: 0, imageSize: 100 }, tablet: { visible: true, fontSize: 85, spacing: 80, layout: 'default', order: 0, imageSize: 80 }, mobile: { visible: true, fontSize: 70, spacing: 60, layout: 'default', order: 0, imageSize: 60 } },
    permissions: { roleVisibility: 'All', passwordProtect: false },
    analytics: { viewCount: 0, clickTracking: true, scrollDepthTracking: false },
    advanced: { customCSS: '', customAttributes: '', customID: '' },
    versionHistory: [],
  },

  cta: {
    type: 'cta',
    name: 'Call to Action Section',
    visible: true,
    published: true,
    order: 0,
    content: {
      title: 'Let\'s Work Together',
      subtitle: 'Have a project in mind?',
      description: 'I\'m always open to discussing new projects, creative ideas, or opportunities to be part of your vision.',
      buttonText: 'Get in Touch',
      buttonUrl: '#contact',
      buttonStyle: 'primary',
      alignment: 'center',
    },
    style: { background: '#1a1a2e', textColor: '#ffffff', headingColor: '#ffffff', linkColor: '#3b82f6', buttonStyle: 'rounded', cardStyle: 'default', iconStyle: 'default', spacing: 'comfortable', shadow: 'none', borderRadius: '0', opacity: 100, hoverState: 'none', focusState: 'none' },
    layout: { containerWidth: 'boxed', padding: '80px 0', margin: '0', sectionHeight: 'auto', alignment: 'center', columns: 1, gap: '0', flexDirection: 'column', sticky: false },
    media: { backgroundImage: '', backgroundVideo: '', overlayColor: 'rgba(0,0,0,0.5)', overlayOpacity: 50, parallax: false },
    seo: { metaTitle: '', metaDescription: '', keywords: '', slug: '', ogTitle: '', ogDescription: '', ogImage: '' },
    animation: { type: 'zoom', duration: 0.8, delay: 0, trigger: 'onScroll', loop: false, scrollAnimation: 'none' },
    responsive: { desktop: { visible: true, fontSize: 100, spacing: 100, layout: 'default', order: 0, imageSize: 100 }, tablet: { visible: true, fontSize: 85, spacing: 80, layout: 'default', order: 0, imageSize: 80 }, mobile: { visible: true, fontSize: 70, spacing: 60, layout: 'default', order: 0, imageSize: 60 } },
    permissions: { roleVisibility: 'All', passwordProtect: false },
    analytics: { viewCount: 0, clickTracking: true, scrollDepthTracking: false },
    advanced: { customCSS: '', customAttributes: '', customID: '' },
    versionHistory: [],
  },

  statistics: {
    type: 'statistics',
    name: 'Statistics Section',
    visible: true,
    published: true,
    order: 0,
    content: {
      title: 'By the Numbers',
      subtitle: 'Some interesting facts',
      description: '',
      columns: 4,
      items: [
        { label: 'Projects Completed', value: '100', suffix: '+' },
        { label: 'Happy Clients', value: '50', suffix: '+' },
        { label: 'Years Experience', value: '10', suffix: '+' },
        { label: 'Technologies', value: '30', suffix: '+' },
      ],
    },
    style: { background: '#f8f9fa', textColor: '#333333', headingColor: '#1a1a2e', linkColor: '#3b82f6', buttonStyle: 'rounded', cardStyle: 'default', iconStyle: 'default', spacing: 'comfortable', shadow: 'none', borderRadius: '0', opacity: 100, hoverState: 'none', focusState: 'none' },
    layout: { containerWidth: 'boxed', padding: '80px 0', margin: '0', sectionHeight: 'auto', alignment: 'center', columns: 4, gap: '24px', flexDirection: 'row', sticky: false },
    media: { backgroundImage: '', backgroundVideo: '', overlayColor: '', overlayOpacity: 0, parallax: false },
    seo: { metaTitle: '', metaDescription: '', keywords: '', slug: '', ogTitle: '', ogDescription: '', ogImage: '' },
    animation: { type: 'fade', duration: 0.6, delay: 0.1, trigger: 'onScroll', loop: false, scrollAnimation: 'none' },
    responsive: { desktop: { visible: true, fontSize: 100, spacing: 100, layout: 'default', order: 0, imageSize: 100 }, tablet: { visible: true, fontSize: 85, spacing: 80, layout: 'grid-2', order: 0, imageSize: 80 }, mobile: { visible: true, fontSize: 70, spacing: 60, layout: 'grid-2', order: 0, imageSize: 60 } },
    permissions: { roleVisibility: 'All', passwordProtect: false },
    analytics: { viewCount: 0, clickTracking: false, scrollDepthTracking: false },
    advanced: { customCSS: '', customAttributes: '', customID: '' },
    versionHistory: [],
  },

  custom: {
    type: 'custom',
    name: 'Custom Section',
    visible: true,
    published: true,
    order: 0,
    content: {
      title: 'Custom Content',
      html: '<div style="padding: 20px; text-align: center;"><h2>Custom Section</h2><p>Add your own HTML content here.</p></div>',
      css: '',
      js: '',
    },
    style: { background: '#ffffff', textColor: '#333333', headingColor: '#1a1a2e', linkColor: '#3b82f6', buttonStyle: 'rounded', cardStyle: 'default', iconStyle: 'default', spacing: 'comfortable', shadow: 'none', borderRadius: '0', opacity: 100, hoverState: 'none', focusState: 'none' },
    layout: { containerWidth: 'boxed', padding: '80px 0', margin: '0', sectionHeight: 'auto', alignment: 'center', columns: 1, gap: '0', flexDirection: 'column', sticky: false },
    media: { backgroundImage: '', backgroundVideo: '', overlayColor: '', overlayOpacity: 0, parallax: false },
    seo: { metaTitle: '', metaDescription: '', keywords: '', slug: '', ogTitle: '', ogDescription: '', ogImage: '' },
    animation: { type: 'fade', duration: 0.6, delay: 0, trigger: 'onLoad', loop: false, scrollAnimation: 'none' },
    responsive: { desktop: { visible: true, fontSize: 100, spacing: 100, layout: 'default', order: 0, imageSize: 100 }, tablet: { visible: true, fontSize: 85, spacing: 80, layout: 'default', order: 0, imageSize: 80 }, mobile: { visible: true, fontSize: 70, spacing: 60, layout: 'default', order: 0, imageSize: 60 } },
    permissions: { roleVisibility: 'All', passwordProtect: false },
    analytics: { viewCount: 0, clickTracking: false, scrollDepthTracking: false },
    advanced: { customCSS: '', customAttributes: '', customID: '' },
    versionHistory: [],
  },
};

export const sectionTypes = [
  { id: 'hero', label: 'Hero', icon: 'M21 15v3a2 2 0 01-2 2H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v3 M3 16l5-5 4 4 3-3 6 6' },
  { id: 'about', label: 'About', icon: 'M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2 M12 3a4 4 0 100 8 4 4 0 000-8z' },
  { id: 'projects', label: 'Projects', icon: 'M22 19a2 2 0 01-2 2H4a2 2 0 01-2-2V5a2 2 0 012-2h5l2 3h9a2 2 0 012 2z' },
  { id: 'skills', label: 'Skills', icon: 'M16 18l6-6-6-6 M8 6l-6 6 6 6' },
  { id: 'experience', label: 'Experience', icon: 'M12 4v16M4 12h16' },
  { id: 'education', label: 'Education', icon: 'M22 10l-10-5L2 10l10 5 10-5z M6 12v5c0 1.66 2.69 3 6 3s6-1.34 6-3v-5' },
  { id: 'certificates', label: 'Certificates', icon: 'M8 21l4-2 4 2-1-4.36L19 12h-5l-2-5-2 5H5l4 4.64L8 21z' },
  { id: 'testimonials', label: 'Testimonials', icon: 'M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z' },
  { id: 'services', label: 'Services', icon: 'M20 7H4a2 2 0 00-2 2v10a2 2 0 002 2h16a2 2 0 002-2V9a2 2 0 00-2-2z M16 7V5a2 2 0 00-2-2h-4a2 2 0 00-2 2v2' },
  { id: 'blog', label: 'Blog', icon: 'M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z M14 2v6h6 M16 13H8 M16 17H8 M10 9H8' },
  { id: 'contact', label: 'Contact', icon: 'M4 6h16M4 10h16M4 14h16M4 18h16' },
  { id: 'gallery', label: 'Gallery', icon: 'M15 8h.01 M4 6h16M4 10h16M4 14h16M4 18h16' },
  { id: 'timeline', label: 'Timeline', icon: 'M12 8V4m0 4a4 4 0 100 8 4 4 0 000-8z M12 20v-4' },
  { id: 'faq', label: 'FAQ', icon: 'M8 10h8 M8 14h6 M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10z' },
  { id: 'cta', label: 'Call to Action', icon: 'M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z M14 2v6h6 M12 18v-6 M9 15h6' },
  { id: 'statistics', label: 'Statistics', icon: 'M3 20h18M5 16l3-5 4 4 5-8 4 4' },
  { id: 'custom', label: 'Custom', icon: 'M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z M14 2v6h6 M16 13H8 M16 17H8 M10 9H8' },
];

export default sectionDefaults;
